version: "3.8"

services:
  app:
    build: .
    command: bash -c "alembic upgrade head && uvicorn rockblock_integration.main:app --host 0.0.0.0 --port 8000 --reload"
    env_file:
      - .env
    ports:
      - "8000:8000"


  database:
    image: postgres:12
    volumes:
      - integration_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5436:5432"
volumes:
  integration_data:
