"""empty message

Revision ID: be9f022b14ee
Revises: 
Create Date: 2023-05-22 10:48:07.959150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be9f022b14ee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integration',
    sa.Column('imei', sa.String(), nullable=True),
    sa.Column('serial', sa.Integer(), nullable=True),
    sa.Column('momsn', sa.Integer(), nullable=True),
    sa.Column('transmit_time', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('iridium_latitude', sa.Float(), nullable=True),
    sa.Column('iridium_longitude', sa.Float(), nullable=True),
    sa.Column('iridium_cep', sa.Float(), nullable=True),
    sa.Column('data', sa.String(), nullable=True),
    sa.Column('JWT', sa.String(), nullable=True),
    sa.Column('device_type', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('creation_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_id'), 'integration', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_integration_id'), table_name='integration')
    op.drop_table('integration')
    # ### end Alembic commands ###
